services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: credicitrus-mssql-local
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "LocalMssql123!"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:

